cc_library(
  name = 'common',
  srcs = [
    'common.c',
  ],
  deps = [
    '//libdrizzle:libdrizzle',
  ]
)

cc_test(
  name = 'column',
  srcs = [
    'column.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'connect',
  srcs = [
    'connect.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'connect_uds',
  srcs = [
    'connect_uds.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'datetypes',
  srcs = [
    'datetypes.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'escape',
  srcs = [
    'escape.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'insert_id',
  srcs = [
    'insert_id.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'nulls',
  srcs = [
    'nulls.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'numbers',
  srcs = [
    'numbers.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'query',
  srcs = [
    'query.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'row',
  srcs = [
    'row.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'statement',
  srcs = [
    'statement.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'statement_char',
  srcs = [
    'statement_char.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'unbuffered_query',
  srcs = [
    'unbuffered_query.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'version',
  srcs = [
    'version.c',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'binlog',
  srcs = [
    'binlog.cc',
  ],
  deps = [
    ':common',
  ]
)

cc_test(
  name = 'version_cxx',
  srcs = [
    'version_cxx.cc',
  ],
  deps = [
    ':common',
  ]
)
